### ISSUE TITLE
CUDA compatibility

### ISSUE THREAD

**Issue by merkys** [kliment-olechnovic/ftdmp#3]
I am trying to run `ftdmp-qa-all` on CUDA 12.2 on a conda environment as described in `README.md`, but it fails with the following:
```
Traceback (most recent call last):
  File "<stdin>", line 20, in <module>
  File "/home/andrius/miniconda3/envs/ftdmp/lib/python3.9/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: 
Unknown builtin op: torch_sparse::ptr2ind.
Could not find any similar ops to torch_sparse::ptr2ind. This op may not exist or may not be currently supported in TorchScript.
```
I suppose this might be due to some CUDA incompatibility. Is there a way to work around it? It might be that PyTorch is not yet updated to use CUDA 12.

**Comment by kliment-olechnovic** [comment]
Hi,

According to the current PyTorch installation guide (https://pytorch.org/get-started/locally/), the stable PyTorch version does not support CUDA 12 yet. You can try PyTorch Nightly, which supports CUDA 12.1, but then I am not sure that PyTorch Geometric will work.

**Comment by merkys** [comment]
Thanks for the suggestion, I will try it out.
